baseURL = 'https://bunyols.xyz/'
languageCode = 'en-us'
title = 'Bunyols | Home'
[taxonomies]
  category = "categories"
  family = "family"
[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
